
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloakdb-pv-0
  labels:
    type: local
spec:
  capacity: 
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/keycloakdb
  claimRef:
    namespace: keycloak
    name: keycloakdb-keycloakdb-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-node