apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kompose.cmd: kompose convert -f docker-compose.yml -o ./.helm/templates
    kompose.service.expose: {{ .Values.host }}
    kompose.service.expose.ingress-class-name: nginx
    kompose.service.expose.tls-secret: keycloak-secret
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: keycloak
  name: keycloak
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - backend:
              service:
                name: keycloak
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - {{ .Values.host }}
      secretName: keycloak-secret
status:
  loadBalancer: {}
